name: 'Manual trigger test'

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (x.y.z)'     
        required: true

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Version: ${{ github.event.inputs.version }}"
