name: 'Manual trigger test 2'

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (x.y.z)'     
        required: true
  push:
    branchs:
      - branch test-trigger-2

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print version number
        run: |
          echo "hello" 
          # "Version: ${{ github.event.inputs.version }}"
